version: '3.8'
services:
  database:
    image: mongo
    restart: always
    container_name: mongodb_auth_service
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:alpine
    container_name: redis_auth_service
    restart: always
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis_auth_service:6379
    ports:
    - "8081:8081"
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher_auth_service
    restart: on-failure
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  mongo-data:
