version: '3.8'
services:
  database:
    image: mongo
    restart: always
    container_name: mongodb_auth_service
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher_auth_service
    restart: on-failure
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  mongo-data:
